[project]
name = "django-chat"
version = "1.0.0"
description = "A quick test to see how django can be used for async chats"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "channels>=4.3.1",
    "daphne>=4.2.1",
    "django>=5.2.6",
]
